### ISSUE TITLE
The sample code doesn't work.

### ISSUE THREAD

**Issue by sonekoki** [jrspruitt/pyfa_gpio#1]
## The sample code doesn't work because of follow error.

File "gpio_test.py", line 9, in <module>
    gpio.gpio_init(40, 1)
  File "/root/scripts/fgpio/fgpio.py", line 87, in gpio_init
    self._gpio_direction(pin, direction)
  File "/root/scripts/fgpio/fgpio.py", line 369, in _gpio_direction
    direction = direction.lower()
  'int' object has no attribute 'lower'

---

system: NanoPi with debian jessie

**Comment by jrspruitt** [comment]
Hi sonekoki,
My apologies, the README was out of date, to make it easier to read, the args were changed to 'in', 'out' for direction, so gpio.gpio_init(40, 'out') would be the correct way. I updated the README to reflect these changes.
Thanks,
-Jason
