### ISSUE TITLE
issue with sample code

### ISSUE THREAD

**Issue by samisabik** [jrspruitt/pyfa_gpio#2]
> gpio.gpio_init(7, 1)
> File "build/bdist.linux-armv7l/egg/fgpio/fgpio.py", line 85, in gpio_init
> File "build/bdist.linux-armv7l/egg/fgpio/fgpio.py", line 465, in _mem_open
> mmap.error: [Errno 1] Operation not permitted

**Comment by samisabik** [comment]
same with gpio.gpio_init(7, "out")

**Comment by jrspruitt** [comment]
Are you running  your script as sudo or root? And on a NanoPi 1?

**Comment by samisabik** [comment]
sudo on a NanoPi M1
do I have to run as root user ?

**Comment by jrspruitt** [comment]
On I'm sorry, this is only for the NanoPi 1, which I believe they don't sell anymore. Its highly doubtful it would work on any of the newer models.

**Comment by samisabik** [comment]
oh right ! OK then i'll look deeper to get some python GPIO programming

**Comment by jrspruitt** [comment]
https://github.com/friendlyarm/matrix You might try here, I'm not exactly sure what boards it supports anymore, but looks like a few of them.
