### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by DEM-DWG** [jrspruitt/pyfa_gpio#3]
Hello!
Unfortunately I have to Nanopi2.
Gives an error message
Traceback (most recent call last):
   File "/var/local/My_projekt/Gpio.py", line 9, in <module>
     gpio.gpio_init (40, 1)
   File "build / bdist.linux-armv7l / egg / fgpio / fgpio.py", line 87, in gpio_init
   File "build / bdist.linux-armv7l / egg / fgpio / fgpio.py", line 369, in _gpio_direction
AttributeError: 'int' object has no attribute 'lower'

**Comment by jrspruitt** [comment]
Hi,

This is for the NanoPi 1, which is no longer available. Unfortunately the structure of the registers involved for the NanoPi2 and the other boards like it, make it fairly incompatible with the code as it is.

-Jason

**Comment by DEM-DWG** [comment]
And not prompt how to convert Nanopi2?
Or how else can you work with GPIO on NanoPi 2 ???
I'm from Russia, anglysky know is bad ... :(

**Comment by jrspruitt** [comment]
HI,

Converting this to NanoPi2 would take some fairly major changes. FriendlyARM has this https://github.com/friendlyarm/matrix-python I've never used it myself though, but should get you gpio access, or the information to at least.

-Jason

**Comment by DEM-DWG** [comment]
Огромное спасибо!!!
Я почему то это не находил....
Thank you so much!!!
For some reason I could not find it ....
